=== MOsama10/radiology-report-generation/src/preprocessing/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["image_id", "objects", "attributes"],
    "properties": {
        "image_id": {"type": "string"},
        "viewpoint": {"type": "string"},
        "patient_id": {"type": ["integer", "string"]},
        "study_id": {"type": ["integer", "string"]},
        "gender": {"type": "string"},
        "age_decile": {"type": "string"},
        "reason_for_exam": {"type": "string"},
        "StudyDateTime": {"type": "string"},
        "StudyOrder": {"type": "integer"},
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["object_id", "bbox_name", "name", "synsets"],
                "properties": {
                    "object_id": {"type": "string"},
                    "x1": {"type": "integer"},
                    "y1": {"type": "integer"},
                    "x2": {"type": "integer"},
                    "y2": {"type": "integer"},
                    "width": {"type": "integer"},
                    "height": {"type": "integer"},
                    "bbox_name": {"type": "string"},
                    "synsets": {"type": "array", "items": {"type": "string"}},
                    "name": {"type": "string"}
                }
            }
        },
        "attributes": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["object_id", "name", "attributes"],
                "properties": {
                    "object_id": {"type": "string"},
                    "name": {"type": "string"},
                    "bbox_name": {"type": "string"},
                    "synsets": {"type": "array", "items": {"type": "string"}},
                    "attributes": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {"type": "string"}
                        }
                    },
                    "phrases": {"type": "array", "items": {"type": "string"}},
                    "phrase_IDs": {"type": "array", "items": {"type": "string"}},
                    "sections": {"type": "array", "items": {"type": "string"}},
                    "comparison_cues": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}},
                    "temporal_cues": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}},
                    "severity_cues": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}},
                    "texture_cues": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}}
                }
            }
        },
        "relationships": {"type": "array"}
    }
}

=== MOsama10/radiology-report-generation/data/raw/00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_SceneGraph.json
{
    "image_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78",
    "viewpoint": "AP",
    "patient_id": 19193776,
    "study_id": 53547436,
    "gender": "M",
    "age_decile": "40-50",
    "reason_for_exam": "___-year-old man, intubated.  Check interval change.",
    "StudyOrder": 2,
    "StudyDateTime": "2129-07-30 06:36:27 UTC",
    "objects": [
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right lung",
            "x1": 25,
            "y1": 51,
            "x2": 97,
            "y2": 164,
            "width": 72,
            "height": 113,
            "bbox_name": "right lung",
            "synsets": [
                "C0225706"
            ],
            "name": "Right lung",
            "original_x1": 341,
            "original_y1": 436,
            "original_x2": 1323,
            "original_y2": 1978,
            "original_width": 982,
            "original_height": 1542
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right upper lung zone",
            "x1": 52,
            "y1": 53,
            "x2": 97,
            "y2": 83,
            "width": 45,
            "height": 30,
            "bbox_name": "right upper lung zone",
            "synsets": [
                "C0934570"
            ],
            "name": "Right upper lung zone",
            "original_x1": 709,
            "original_y1": 463,
            "original_x2": 1323,
            "original_y2": 873,
            "original_width": 614,
            "original_height": 410
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right mid lung zone",
            "x1": 38,
            "y1": 83,
            "x2": 95,
            "y2": 112,
            "width": 57,
            "height": 29,
            "bbox_name": "right mid lung zone",
            "synsets": [
                "CL380307"
            ],
            "name": "Right mid lung zone",
            "original_x1": 518,
            "original_y1": 873,
            "original_x2": 1296,
            "original_y2": 1268,
            "original_width": 778,
            "original_height": 395
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right lower lung zone",
            "x1": 25,
            "y1": 112,
            "x2": 95,
            "y2": 164,
            "width": 70,
            "height": 52,
            "bbox_name": "right lower lung zone",
            "synsets": [
                "C0929214"
            ],
            "name": "Right lower lung zone",
            "original_x1": 341,
            "original_y1": 1268,
            "original_x2": 1296,
            "original_y2": 1978,
            "original_width": 955,
            "original_height": 710
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right hilar structures",
            "x1": 66,
            "y1": 77,
            "x2": 96,
            "y2": 117,
            "width": 30,
            "height": 40,
            "bbox_name": "right hilar structures",
            "synsets": [
                "C1708369"
            ],
            "name": "Hilar Area of the Right Lung",
            "original_x1": 900,
            "original_y1": 791,
            "original_x2": 1309,
            "original_y2": 1337,
            "original_width": 409,
            "original_height": 546
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right apical zone",
            "x1": 63,
            "y1": 51,
            "x2": 97,
            "y2": 63,
            "width": 34,
            "height": 12,
            "bbox_name": "right apical zone",
            "synsets": [
                "C0929167"
            ],
            "name": "Apical zone of right lung",
            "original_x1": 859,
            "original_y1": 436,
            "original_x2": 1323,
            "original_y2": 600,
            "original_width": 464,
            "original_height": 164
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right costophrenic angle",
            "x1": 15,
            "y1": 150,
            "x2": 35,
            "y2": 170,
            "width": 20,
            "height": 20,
            "bbox_name": "right costophrenic angle",
            "synsets": [
                "CL380392",
                "C0504099"
            ],
            "name": "right costophrenic sulcus;;Right costodiaphragmatic recess",
            "original_x1": 204,
            "original_y1": 1787,
            "original_x2": 477,
            "original_y2": 2060,
            "original_width": 273,
            "original_height": 273
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right cardiophrenic angle",
            "x1": 65,
            "y1": 128,
            "x2": 80,
            "y2": 156,
            "width": 15,
            "height": 28,
            "bbox_name": "right cardiophrenic angle",
            "synsets": [
                "CL380389"
            ],
            "name": "right cardiophrenic sulcus",
            "original_x1": 886,
            "original_y1": 1487,
            "original_x2": 1091,
            "original_y2": 1869,
            "original_width": 205,
            "original_height": 382
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_right hemidiaphragm",
            "x1": 25,
            "y1": 136,
            "x2": 107,
            "y2": 164,
            "width": 82,
            "height": 28,
            "bbox_name": "right hemidiaphragm",
            "synsets": [
                "C0929193"
            ],
            "name": "Right hemidiaphragm",
            "original_x1": 341,
            "original_y1": 1596,
            "original_x2": 1459,
            "original_y2": 1978,
            "original_width": 1118,
            "original_height": 382
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left lung",
            "x1": 107,
            "y1": 44,
            "x2": 183,
            "y2": 125,
            "width": 76,
            "height": 81,
            "bbox_name": "left lung",
            "synsets": [
                "C0225730"
            ],
            "name": "Left lung",
            "original_x1": 1459,
            "original_y1": 341,
            "original_x2": 2496,
            "original_y2": 1446,
            "original_width": 1037,
            "original_height": 1105
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left upper lung zone",
            "x1": 107,
            "y1": 47,
            "x2": 173,
            "y2": 83,
            "width": 66,
            "height": 36,
            "bbox_name": "left upper lung zone",
            "synsets": [
                "C0929215"
            ],
            "name": "Left upper lung zone",
            "original_x1": 1459,
            "original_y1": 382,
            "original_x2": 2360,
            "original_y2": 873,
            "original_width": 901,
            "original_height": 491
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left mid lung zone",
            "x1": 109,
            "y1": 83,
            "x2": 182,
            "y2": 98,
            "width": 73,
            "height": 15,
            "bbox_name": "left mid lung zone",
            "synsets": [
                "CL380306"
            ],
            "name": "Left mid lung zone",
            "original_x1": 1487,
            "original_y1": 873,
            "original_x2": 2483,
            "original_y2": 1077,
            "original_width": 996,
            "original_height": 204
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left lower lung zone",
            "x1": 112,
            "y1": 98,
            "x2": 183,
            "y2": 125,
            "width": 71,
            "height": 27,
            "bbox_name": "left lower lung zone",
            "synsets": [
                "C0934571"
            ],
            "name": "Left lower lung zone",
            "original_x1": 1528,
            "original_y1": 1077,
            "original_x2": 2496,
            "original_y2": 1446,
            "original_width": 968,
            "original_height": 369
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left hilar structures",
            "x1": 108,
            "y1": 80,
            "x2": 145,
            "y2": 101,
            "width": 37,
            "height": 21,
            "bbox_name": "left hilar structures",
            "synsets": [
                "C1708367"
            ],
            "name": "Hilar Area of the Left Lung",
            "original_x1": 1473,
            "original_y1": 832,
            "original_x2": 1978,
            "original_y2": 1118,
            "original_width": 505,
            "original_height": 286
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left apical zone",
            "x1": 109,
            "y1": 44,
            "x2": 160,
            "y2": 63,
            "width": 51,
            "height": 19,
            "bbox_name": "left apical zone",
            "synsets": [
                "C0929168"
            ],
            "name": "Apical zone of left lung",
            "original_x1": 1487,
            "original_y1": 341,
            "original_x2": 2182,
            "original_y2": 600,
            "original_width": 695,
            "original_height": 259
        },
        {
            "object_id": "00f11709-ce2637cf-d7e74371-0fe48659-f3c88f78_left costophrenic angle",
            "x1": 173,
            "y1": 100,
            "x2": 193,
            "y2": 120,
            "width": 20,
            "height": 20,
            "bbox_name": "left costophrenic angle",
            "synsets": [
                "CL380391",
